
baseURL = 'https://ceald.cc'
languageCode = 'en-US'
title = "Ceald's Blog"

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
# this is needed when you fetch the theme as a submodule to your repo.
[[module.imports]]
path = "./moonlit"

[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = ""
site = ""

[params]
github = "https://github.com/Ceald1"
linkedin = ''
email = ''
#twitter = ''
hackthebox = 'https://app.hackthebox.com/profile/440221'
